# Generated by Django 6.1.1 on 2026-10-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Време за приготвяне (в минути)')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Bрой порции')),
            ],
            options={
                'verbose_name': 'Ястие',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='meals.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Продукт в рецептата',
                'ordering': ['dish', 'product'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(related_name='dishes', through='meals.RecipeItem', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('dish', 'product'), name='unique_product_per_dish'),
        ),
    ]
