# Generated by Django 6.1.1 on 2026-10-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Store',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Продукт')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Марка')),
                ('category', models.CharField(choices=[('meat_fish_eggs', 'Месо, риба, яйца'), ('milk_cheese', 'Млекопродукти'), ('fruit_vegetables', 'Плодове и зеленчуци'), ('grains_legumes', 'Зърнени и бобови'), ('nuts', 'Ядки'), ('oils', 'Масла'), ('sweets', 'Сладки и десерти'), ('drinks', 'Напитки'), ('packaged_foods', 'Пакетирани храни'), ('spices', 'Подправки')], max_length=30, verbose_name='Категория')),
                ('unit', models.CharField(choices=[('g', 'грама'), ('ml', 'мл'), ('pcs', 'бр')], max_length=3, verbose_name='Мерна единица')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('price_unit', models.CharField(choices=[('kg', 'кг'), ('liter', 'литър'), ('package', 'опаковка')], max_length=10, verbose_name='Цена за')),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Калории (kcal)')),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белтъчини (g/100g)')),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Въглехидрати (g/100g)')),
                ('fats_per_100g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Мазнини (g/100g)')),
                ('is_basic', models.BooleanField(default=False, help_text='Базов продукт - винаги трябва да има в наличност', verbose_name='Основен продукт')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'ordering': ['name'],
                'unique_together': {('name', 'brand', 'store')},
            },
        ),
    ]
