# Generated by Django 6.1.1 on 2026-10-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='Налично количество')),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='Минимално количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Продукт')),
            ],
        ),
    ]
